site:
  key: rossmann
  entry_url: "https://www.rossmann.pl/"

sections:
  # Sekcja 1 – hero slider
  - name: hero_slider
    input: {type: css, value: "section[class*=AutoPlayBanner-module_wideContainer]"}
    list:
      item_selector: "picture"
      fields:
        - {name: desktop_image, type: image, selector: "img", attr: src}
        - {name: mobile_srcset, type: srcset, selector: "source", attr: srcset}
        - {name: alt, type: attr, selector: "img", attr: alt}
        - {name: cta_href, type: attr, selector: "a", attr: href}
        - {name: title, type: text_optional, selector: ".h1, .h2, .h3, .label-large"}
    validation:
      min_count: 1

  # Sekcja 2 – promocje (grid)
  - name: promos
    input: {type: css, value: "div[data-testid='product-container']"}
    list:
      item_selector: "div[data-testid='product-container']"
      fields:
        - {name: image_url, type: image, selector: "img[data-testid='product-image']", attr: src}
        - {name: alt, type: attr, selector: "img[data-testid='product-image']", attr: alt}
        - {name: brand, type: text, selector: "[data-testid='product-brand']"}
        - {name: caption, type: text, selector: "[data-testid='product-caption']"}
        - {name: price_text, type: price_text, selector: "[data-testid='product-price']"}
        - {name: lowest_30, type: text_optional, selector: "[data-testid='lowest-price-in-30-days'], .styles-module_strike--3Okb2"}
        - {name: badge, type: text_optional, selector: ".styles-module_badge--ptqlS"}
        - {name: link, type: attr, selector: "a[href]", attr: href}
    validation:
      min_count: 4

  # Sekcja 3 – baner graficzny
  - name: banner_graphic
    input: {type: css, value: "img[alt*='Łap wspomnienia'], img[alt*='fotoprodukty']"}
    fields:
      - {name: image_url, type: image, selector: ":self", attr: src}
      - {name: alt, type: attr, selector: ":self", attr: alt}
    validation:
      min_count: 1

  # Sekcja 4 – slider produktowy podobny do gridu
  - name: section4_product_slider
    input: {type: css, value: "div[data-testid='product-container']"}
    list:
      item_selector: "div[data-testid='product-container']"
      fields:
        - {name: image_url, type: image, selector: "img[data-testid='product-image']", attr: src}
        - {name: alt, type: attr, selector: "img[data-testid='product-image']", attr: alt}
        - {name: brand, type: text, selector: "[data-testid='product-brand']"}
        - {name: caption, type: text, selector: "[data-testid='product-caption']"}
        - {name: price_text, type: price_text, selector: "[data-testid='product-price']"}
        - {name: lowest_30, type: text_optional, selector: "[data-testid='lowest-price-in-30-days'], .styles-module_strike--3Okb2"}
        - {name: badge, type: text_optional, selector: ".styles-module_badge--ptqlS"}
        - {name: link, type: attr, selector: "a[href]", attr: href}
    validation:
      min_count: 4
