name: scrape-rossmann

on:
  workflow_dispatch:
  schedule:
    - cron: '30 4 * * *'    # 06:30 w Warszawie (lato)

jobs:
  scrape:
    runs-on: ubuntu-latest

    # Obraz z gotowym Playwrightem i przeglądarkami
    container:
      image: mcr.microsoft.com/playwright/python:v1.45.0-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upgrade pip + install deps
        run: |
          python -m pip install --upgrade pip setuptools wheel
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi

      - name: Run scraper
        run: |
          python -m scraper.runner --site rossmann --profiles desktop,mobile --headless true --save-snapshots true

      - name: Upload artifact (data/)
        uses: actions/upload-artifact@v4
        with:
          name: data-${{ github.run_id }}
          path: data/**
