name: scrape-rossmann

on:
  workflow_dispatch:        # ręczne odpalanie z UI
  schedule:
    - cron: '30 4 * * *'    # codziennie 06:30 Europe/Warsaw (latem); 05:30 zimą

jobs:
  scrape:
    runs-on: ubuntu-latest

    # KLUCZ: odpalamy w obrazie z już zainstalowanymi przeglądarkami Playwright
    container:
      image: mcr.microsoft.com/playwright/python:v1.45.0-jammy

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Jeśli masz requirements.txt – zainstaluje; jeśli nie, spróbuje z pyproject (editable)
      - name: Install Python deps
        run: |
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          if [ -f pyproject.toml ]; then
            python -m pip install -e .
          fi

      - name: Run scraper
        run: |
          python -m scraper.runner --site rossmann --profiles desktop,mobile --headless true --save-snapshots true

      - name: Upload artifact (data/)
        uses: actions/upload-artifact@v4
        with:
          name: data-${{ github.run_id }}
          path: data/**
